version: "3.4"

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    image: aws-api-gateway-ruby/auth
    container_name: api-gateway-auth
    tty: true
    env_file:
      - .env
    working_dir: /workspace/
    volumes:
      - type: bind
        source: $PWD
        target: /workspace/aws-api-gateway-ruby

networks:
  shared-network:
    external: true
